import fs from "node:fs";
import path from "node:path";
import type { Plugin } from "vite";

const PAGES_DIR = path.resolve(process.cwd(), "src/pages");
const OUTPUT_FILE = path.join(PAGES_DIR, "_pageManifest.ts");

type PageFile = {
  // путь относительно src/pages без расширения по типу "posts/[id]"
  moduleId: string;
  // экспрессовский роут по типу "/posts/:id"
  route: string;
};

// собираем полный путь ко всем .tsx файлам страниц
const collectPageFiles = (dir: string): string[] => {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    if (entry.name.startsWith("_")) return [];
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) return collectPageFiles(fullPath);
    if (entry.isFile() && entry.name.endsWith(".tsx")) return [fullPath];
    return [];
  });
};

// конвертируем moduleId в экспрессовский роут ("index" → "/", "[id]" → ":id")
const moduleIdToRoute = (moduleId: string): string => {
  const segments = moduleId.split("/");
  if (segments[segments.length - 1] === "index") segments.pop();

  const route =
    "/" +
    segments
      .map((seg) => (/^\[.+\]$/.test(seg) ? `:${seg.slice(1, -1)}` : seg))
      .join("/");

  return route.length > 1 ? route.replace(/\/$/, "") : "/";
};

const collectPages = (): PageFile[] => {
  return collectPageFiles(PAGES_DIR)
    .map((fullPath) =>
      path
        .relative(PAGES_DIR, fullPath)
        .split(path.sep)
        .join("/")
        .replace(/\.tsx$/, ""),
    )
    .map((moduleId) => ({ moduleId, route: moduleIdToRoute(moduleId) }))
    .sort((a, b) => {
      const dynA = (a.route.match(/:/g) ?? []).length;
      const dynB = (b.route.match(/:/g) ?? []).length;
      return dynA - dynB || a.route.localeCompare(b.route);
    });
};

const generateManifest = (pages: PageFile[]): string => {
  const imports = pages
    .map((page, i) => `import * as page${i} from "./${page.moduleId}";`)
    .join("\n");

  const entries = pages
    .map(
      (page, i) =>
        `  ${JSON.stringify(page.route)}: toEntry(page${i}, ${JSON.stringify(
          page.moduleId,
        )}),`,
    )
    .join("\n");

  return `// AUTO-GENERATED by plugins/vite-plugin-pages.ts
import type { ComponentType } from "react";
import type { GetServerSideProps, GetStaticProps } from "@/shared/types";
${imports}

type PageModule = {
  default: ComponentType<any>;
  getServerSideProps?: GetServerSideProps<any>;
  getStaticProps?: GetStaticProps<any>;
};

type PageEntry = {
  Component: ComponentType<any>;
  getServerSideProps?: GetServerSideProps<any>;
  getStaticProps?: GetStaticProps<any>;
  moduleId: string;
};

const toEntry = (mod: PageModule, moduleId: string): PageEntry => {
  if (mod.getServerSideProps && mod.getStaticProps) {
    throw new Error(
      \`Page "\${moduleId}" exports both getServerSideProps and getStaticProps — choose one\`,
    );
  }
  return {
    Component: mod.default,
    getServerSideProps: mod.getServerSideProps,
    getStaticProps: mod.getStaticProps,
    moduleId,
  };
};

export const pageManifest: Record<string, PageEntry> = {
${entries}
};
`;
};

// если контент манифеста изменился, то записываем новый
export const writePageManifest = () => {
  const next = generateManifest(collectPages());
  const prev = fs.existsSync(OUTPUT_FILE)
    ? fs.readFileSync(OUTPUT_FILE, "utf-8")
    : "";
  if (prev !== next) fs.writeFileSync(OUTPUT_FILE, next);
};

export const pagesPlugin = (): Plugin => ({
  name: "vite-plugin-pages",
  buildStart() {
    writePageManifest();
  },
});
