import fs from "node:fs";
import path from "node:path";
import type { Plugin } from "vite";

const PAGES_DIR = path.resolve(process.cwd(), "src/pages");
const OUTPUT_FILE = path.join(PAGES_DIR, "_pageManifest.ts");

type PageFile = {
  /** Path relative to src/pages without extension, e.g. "posts/[id]". */
  moduleId: string;
  /** Express route, e.g. "/posts/:id". */
  route: string;
};

/** Recursively collect page files, skipping anything prefixed with "_". */
const collectPageFiles = (dir: string): string[] => {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    if (entry.name.startsWith("_")) return [];
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) return collectPageFiles(fullPath);
    if (entry.isFile() && entry.name.endsWith(".tsx")) return [fullPath];
    return [];
  });
};

/** Convert a moduleId into an Express route ("index" → "/", "[id]" → ":id"). */
const moduleIdToRoute = (moduleId: string): string => {
  const segments = moduleId.split("/");
  if (segments[segments.length - 1] === "index") segments.pop();

  const route =
    "/" +
    segments
      .map((seg) =>
        /^\[.+\]$/.test(seg) ? `:${seg.slice(1, -1)}` : seg,
      )
      .join("/");

  return route.length > 1 ? route.replace(/\/$/, "") : "/";
};

const collectPages = (): PageFile[] => {
  return collectPageFiles(PAGES_DIR)
    .map((fullPath) =>
      path
        .relative(PAGES_DIR, fullPath)
        .split(path.sep)
        .join("/")
        .replace(/\.tsx$/, ""),
    )
    .map((moduleId) => ({ moduleId, route: moduleIdToRoute(moduleId) }))
    .sort((a, b) => {
      // Register static routes before dynamic ones.
      const dynA = (a.route.match(/:/g) ?? []).length;
      const dynB = (b.route.match(/:/g) ?? []).length;
      return dynA - dynB || a.route.localeCompare(b.route);
    });
};

const generateManifest = (pages: PageFile[]): string => {
  const imports = pages
    .map((page, i) => `import * as page${i} from "./${page.moduleId}";`)
    .join("\n");

  const entries = pages
    .map(
      (page, i) =>
        `  ${JSON.stringify(page.route)}: toEntry(page${i}, ${JSON.stringify(
          page.moduleId,
        )}),`,
    )
    .join("\n");

  return `// AUTO-GENERATED by plugins/vite-plugin-pages.ts — do not edit by hand.
import type { ComponentType } from "react";
import type { GetServerSideProps } from "@/shared/types";
${imports}

type PageModule = {
  default: ComponentType<any>;
  getServerSideProps?: GetServerSideProps<any>;
};

export type PageEntry = {
  Component: ComponentType<any>;
  getServerSideProps?: GetServerSideProps<any>;
  moduleId: string;
};

const toEntry = (mod: PageModule, moduleId: string): PageEntry => ({
  Component: mod.default,
  getServerSideProps: mod.getServerSideProps,
  moduleId,
});

export const pageManifest: Record<string, PageEntry> = {
${entries}
};
`;
};

/** Write the manifest, but only when its content actually changed. */
export const writePageManifest = () => {
  const next = generateManifest(collectPages());
  const prev = fs.existsSync(OUTPUT_FILE)
    ? fs.readFileSync(OUTPUT_FILE, "utf-8")
    : "";
  if (prev !== next) fs.writeFileSync(OUTPUT_FILE, next);
};

export const pagesPlugin = (): Plugin => ({
  name: "vite-plugin-pages",
  buildStart() {
    writePageManifest();
  },
});
