// AUTO-GENERATED by plugins/vite-plugin-pages.ts — do not edit by hand.
import type { ComponentType } from "react";
import type { GetServerSideProps } from "@/shared/types";
import * as page0 from "./index";
import * as page1 from "./static";
import * as page2 from "./posts/[id]";

type PageModule = {
  default: ComponentType<any>;
  getServerSideProps?: GetServerSideProps<any>;
};

export type PageEntry = {
  Component: ComponentType<any>;
  getServerSideProps?: GetServerSideProps<any>;
  moduleId: string;
};

const toEntry = (mod: PageModule, moduleId: string): PageEntry => ({
  Component: mod.default,
  getServerSideProps: mod.getServerSideProps,
  moduleId,
});

export const pageManifest: Record<string, PageEntry> = {
  "/": toEntry(page0, "index"),
  "/static": toEntry(page1, "static"),
  "/posts/:id": toEntry(page2, "posts/[id]"),
};
